global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

accessLog:
  format: "common"
  fields:
    names:
      StartUTC: drop

api:
 dashboard: true
 debug: true

ping:
 entryPoint: websecure

providers:
 docker:
   endpoint: unix:///var/run/docker.sock
   exposedByDefault: false
   network: proxy

certificatesResolvers:
  lets_encrypt_resolver:
    acme:
      email: sal18014@byui.edu
      storage: acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      tlsChallenge: {}
      # httpChallenge:
      #   entrypoint: web
      # dnsChallenge:
      #   provider: cloudflare
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "1.0.0.1:53"
