global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  websecure:
    address: :443

accessLog:
  format: "common"
  fields:
    names:
      StartUTC: drop

api:
 dashboard: true
 debug: true

ping:
 entryPoint: websecure

providers:
 docker:
   endpoint: unix:///var/run/docker.sock
   exposedByDefault: false
   network: proxy

certificatesResolvers:
  cloudflare:
    acme:
      email: salsonn@outlook.com
      storage: acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
